@Bookistry.API_HostAddress = https://localhost:7075



POST {{Bookistry.API_HostAddress}}/auth/sign-up
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "dfg@gmail.com",
  "password": "p@ssworS123",
  "ConfirmPassword": "p@ssworS123"

}

###
